# Generated by Django 3.0.4 on 2020-03-20 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, default='images/avatar.jpg', upload_to='images')),
                ('entreprise', models.CharField(max_length=100, null=True)),
                ('mots_cles', models.CharField(max_length=200, null=True, verbose_name='Technologies utilisées')),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aine',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pro_it.Personne')),
                ('niveau', models.CharField(max_length=50, null=True, verbose_name='Statut')),
                ('filiere_faite', models.CharField(max_length=50, null=True, verbose_name='Filière faite ou en cours')),
            ],
            bases=('pro_it.personne',),
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pro_it.Personne')),
                ('filiere_cours', models.CharField(max_length=50, null=True)),
                ('projet_titre', models.CharField(max_length=100, null=True, verbose_name='Titre du projet')),
                ('description', models.CharField(max_length=200, null=True)),
                ('parrain', models.ManyToManyField(related_name='filieuls', to='pro_it.Aine')),
            ],
            bases=('pro_it.personne',),
        ),
    ]
