# Generated by Django 3.0.4 on 2020-03-20 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_it', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='date_naissance',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='aine',
            name='filiere_faite',
            field=models.CharField(choices=[('SIGL', 'SIGL'), ('SITW', 'SITW'), ('RTEL', 'RTEL'), ('MDSI', 'MDSI'), ('MBDS', 'MBDS')], max_length=50, null=True, verbose_name='Filière faite ou en cours'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='password',
            field=models.CharField(max_length=200, null=True, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Brève description'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='filiere_cours',
            field=models.CharField(choices=[('SRIT', 'SRIT'), ('SIGL', 'SIGL'), ('RTEL', 'RTEL')], max_length=50, null=True, verbose_name='Filière'),
        ),
    ]
