# Generated by Django 3.0.4 on 2020-03-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_it', '0002_auto_20200320_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='filiere_cours',
            field=models.CharField(choices=[('SRIT', 'SRIT'), ('SIGL', 'SIGL'), ('RTEL', 'RTEL')], max_length=50, null=True, verbose_name='Titre du projet'),
        ),
    ]
