# Generated by Django 3.0.4 on 2020-03-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_it', '0003_auto_20200320_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_actualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualité')),
                ('description', models.CharField(max_length=500, null=True)),
                ('nbre_jaime', models.IntegerField(default=0)),
                ('nbre_com', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='aine',
            name='niveau',
            field=models.CharField(choices=[('PROFESSIONNEL', 'PROFESSIONNEL'), ('ETUDIANT', 'ETUDIANT')], max_length=50, null=True, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='filiere_cours',
            field=models.CharField(choices=[('SRIT', 'SRIT'), ('SIGL', 'SIGL'), ('RTEL', 'RTEL')], max_length=50, null=True, verbose_name='Filière'),
        ),
    ]
