# Generated by Django 3.0.4 on 2020-03-27 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_it', '0004_auto_20200327_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_actualite',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.time(16, 58, 59, 33145), null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/avatar.jpg', upload_to='avatar'),
        ),
    ]
