# Generated by Django 3.0.4 on 2020-03-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_it', '0005_auto_20200327_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo_actualite',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='personne',
            name='genre',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
