# Generated by Django 3.0.4 on 2020-03-28 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_it', '0006_auto_20200328_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='genre',
        ),
    ]
