# Generated by Django 3.0.4 on 2020-03-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_it', '0007_remove_personne_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='genre',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
