# Generated by Django 3.0.4 on 2020-03-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_it', '0008_personne_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='couverture',
            field=models.ImageField(blank=True, default='couverture/avatar.jpg', upload_to='couverture'),
        ),
        migrations.AddField(
            model_name='personne',
            name='promo',
            field=models.CharField(choices=[('IT 01', 'IT 01'), ('IT 02', 'IT 02'), ('IT 03', 'IT 03'), ('IT 04', 'IT 04'), ('IT 05', 'IT 05'), ('IT 06', 'IT 06')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aine',
            name='filiere_faite',
            field=models.CharField(choices=[('', 'Choisissez votre filière'), ('SIGL', 'SIGL'), ('SITW', 'SITW'), ('RTEL', 'RTEL'), ('MDSI', 'MDSI'), ('MBDS', 'MBDS')], max_length=50, null=True, verbose_name='Filière faite ou en cours'),
        ),
        migrations.AlterField(
            model_name='aine',
            name='niveau',
            field=models.CharField(choices=[('', 'Votre Statut'), ('PROFESSIONNEL', 'PROFESSIONNEL'), ('ETUDIANT', 'ETUDIANT')], max_length=50, null=True, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='genre',
            field=models.CharField(choices=[('HOMME', 'HOMME'), ('FEMME', 'FEMME')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='filiere_cours',
            field=models.CharField(choices=[('', 'Choisissez votre filière'), ('SRIT', 'SRIT'), ('TWIN', 'TWIN'), ('SIGL', 'SIGL'), ('RTEL', 'RTEL')], max_length=50, null=True, verbose_name='Filière'),
        ),
    ]
