# Generated by Django 3.0.4 on 2020-04-04 11:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro_it', '0009_auto_20200328_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_faits', to='pro_it.Personne')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=1000, null=True)),
                ('date_publication', models.DateTimeField(default=datetime.datetime(2020, 4, 4, 11, 44, 34, 895058), null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pro_it.Personne')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(blank=True, max_length=50, null=True)),
                ('contenu', models.CharField(max_length=100, null=True)),
                ('proprio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notifications', to='pro_it.Personne')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualité')),
                ('description', models.CharField(max_length=500, null=True)),
                ('publication_date', models.DateTimeField(blank=True, default=datetime.time(11, 44, 34, 895486), null=True)),
                ('nbre_com', models.IntegerField(default=0)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='pro_it.Personne')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo_actualite',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_ecrits', to='pro_it.Publication'),
        ),
    ]
