# Generated by Django 3.0.4 on 2020-04-04 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro_it', '0010_auto_20200404_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='destinateur',
            field=models.ManyToManyField(related_name='messages_reçus', to='pro_it.Personne'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyés', to='pro_it.Personne'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_publication',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 22, 23, 23, 146431), null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=datetime.time(22, 23, 23, 147433), null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='pro_it.Groupe'),
        ),
    ]
